name: WorldEditPlus
main: WorldEditPlus\WorldEditPlus
version: 1.1
api: 3.1.1
author: CreeParker
website: https://twitter.com/cree_parker
commands:
  fill:
    description: 領域の一部または全体を指定したブロックで埋める。
    usage: /fill
    permission: op
  clone:
    description: 1つの領域から別の領域にブロックを複製する。
    usage: /clone
    permission: op
  cancel:
    description: 現在の実行中の処理を止めます。
    usage: /cancel
    permission: op
  e:
    description: 始点と終点を消去します。
    usage: /e
    permission: op