name: WorldEditPlus
main: WorldEditPlus\WorldEditPlus
version: 0.5
api: 3.1.1
author: CreeParker
website: https://twitter.com/cree_parker
commands:
  fill:
    description: 領域の一部または全体を指定したブロックで埋める。
    usage: /fill
    permission: op
  clone:
    description: 1つの領域から別の領域にブロックを複製する。
    usage: /clone
    permission: op
  undo:
    description: 変更した領域のバックアップを復元します。
    usage: /undo <バックアップナンバー>
    permission: op
  cancel:
    description: 現在の実行中の処理を止めます。
    usage: /cancel
    permission: op
  e:
    description: 始点と終点を消去します。
    usage: /e
    permission: op
  sphere:
    description: 球を作る。
    usage: /sphere
    permission: op
  cylinder:
    description: 円を作る。
    usage: /cylinder
    permission: op