name: WorldEditPlus
main: WorldEditPlus\WorldEditPlus
version: 2.5
api: [3.0.0, 4.0.0]
author: CreeParker (@cree_parker)
description: このプラグインは、ワールドエディッタです。
website: https://forum.mcbe.jp/resources/107/
depend: FormAPI
commands:
  fill:
    description: 領域の一部または全体を指定したブロックで埋める。
    usage: /fill <x1> <y1> <z1> <x2> <y2> <z2> <block> [set|outline|hollow|keep|replace] [block]
    permission: worldeditplus.command.fill
  clone:
    description: 1つの領域から別の領域にブロックを複製する。
    usage: /clone <x1> <y1> <z1> <x2> <y2> <z2> <x3> <y3> <z3> [replace|filtered|masked] [normal|force|move] [block] 
    permission: worldeditplus.command.clone
  cylinder:
    description: 円柱の形を作ります。
    usage: /cylinder <x1> <y1> <z1> <x2> <y2> <z2> <block> <x|y|z>
    permission: worldeditplus.command.cylinder
  sphere:
    description: 球の形を作ります。
    usage: /sphere <x1> <y1> <z1> <x2> <y2> <z2> <block>
    permission: worldeditplus.command.sphere
  cancel:
    description: 現在の実行中の処理を止めます。
    usage: /cancel
    permission: worldeditplus.command.cancel
  wand:
    description: 始点と終点を決める斧を取り出します。
    usage: /wand
    permission: worldeditplus.command.wand
  pos1:
    description: 始点を設定します。
    usage: /pos1 [x] [y] [z]
    permission: worldeditplus.command.pos1
  pos2:
    description: 終点を設定します。
    usage: /pos2 [x] [y] [z]
    permission: worldeditplus.command.pos2