# 使用する言語ファイルを選択できます。
# 言語ファイルは「language」フォルダにあります。
# また言語ファイルから文字を変更することができます。
language: "jpn"

# 一度に処理するブロックの量を変えられます。
# 数字が少ないほど鯖への負荷は軽減できますが処理速度が遅くなります。
# 逆に数字が多いほど鯖への負荷が多くなる代わりに処理速度が早くなりますが、
# 負荷が多くなると処理速度に影響がでますのので推奨はしません。
# 基準としては 500～1000 くらいがおススメです。
stopper: 500

# stopperで指定した数のブロックを設置した際に停止する時間を変えれます。
# (1秒÷20)になっていますので 1 だと 0.05秒 になります。
# 秒数を増やすことで複数実行した時の負担を軽減できます。
# 基準としては 1～5 くらいがおススメです。
period: 1